### PR TITLE
feat(dropdown): addition of (vertical) descriptions to menu item template

### PR DESCRIPTION
**Pull request by jamessampford**
## Description
Adds additional options to `remoteData` to allow a description to be created and also allows to specify if using/wanting a vertical description

image

## Testcase
https://jsfiddle.net/lubber/ywpLuk4c/3/

Relates to #1845

### CODE REVIEW

**Review by lubber-de — APPROVED** [review]
LGTM
I added an example jsfiddle to your description. It's not only related to remote content, but also for local values given by the `values` setting

**Review by prudho — APPROVED** [review]
LGTM, and good job ! Messing with dropdown is a bold move 😄

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/265

**Comment by lubber-de** [comment]
@all-contributors please add @jamessampford for code

**Pull request merged**
