### PR TITLE
feat(toast): new centered variant to display in the middle of the screen

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
This PR adds a new `centered` variant to the toast position to be able to display them in the middle of the screen

```javascript
$('body').toast({
  message: 'I am so centered',
  position: 'centered'
})
```

## Testcase
https://jsfiddle.net/lubber/x3w1gsht/13/

## Screenshot
image

### CODE REVIEW

**Review by prudho — APPROVED** [review]
LGTM 👍

I think we can also implement mixed classes like `top centered` and `bottom centered`.

**Comment by lubber-de** [comment]
> LGTM 👍
> 
> I think we can also implement mixed classes like `top centered` and `bottom centered`.

Those already exist 😉 as `top center` and `bottom center`

**Comment by prudho** [comment]
Haha, nevermind 😝

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/301

**Pull request merged**
