### PR TITLE
feat(dropdown): change forceSelection default to false

### LINKED ISSUE #1742: [Dropdown] Search selection selects first item on close
# Bug Report
If you open a searchable dropdown and don't choose any item but closing the dropdown (clicking outside / clicking the dropdown arrow / press ESC) the first item of the results will be selected.

## Steps to reproduce

1. Go to https://fomantic-ui.com/modules/dropdown.html#search-selection
2. Click on the selection dropdown with placeholder "Select Country"
3. Don't select an item
4. Close the dropdown

## Expected result
No selected value.

## Actual result
Afghanistan :-/

## Version

2.x.x

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
This PR changes default value for `forceSelection` to `false`, because if you click into a dropdownfield and click outside again, the first dropdown value will be selected automatically which is probably not wanted in most cases so it shouldn't be the default.

If a `select` HTML field to be converted into a FUI dropdownfield got a  ` required`  attribute, the `forceSelection` setting will be set to `true` again automatically

As this is a breaking change it is supposed to be part of 2.9

## Closes
#1742

### CODE REVIEW

**Review by exoego — APPROVED** [review]
Changing this default sounds reasonable.

**Review by prudho — APPROVED** [review]
LGTM

**Review by ko2in — APPROVED** [review]
LGTM.

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/294

**Pull request merged**
