### PR TITLE
fix(sidebar,flyout,modal): missing identical features and fixes

### LINKED ISSUE #2457: [flyout] basic + left actions buttons
# Feature Request
Similar to #2395 really, can we add a basic version (without borders and using the same background) as well as having the option to left align the buttons?

### PR DESCRIPTION
**Pull request by lubber-de**
### flyout features  (all adopted from modal)
- moved many values into LESS variables
- a11y: aria labels, tab focus trap, close icon focussable and activateable via space key
- `autofocus` setting,`restoreFocus` setting
- fetch esc key to close flyout by new via `keyBoardShortcuts` setting
- basic actions, basic header
- left actions
- center aligned header, content, actions
- `blurring` setting

### flyout fixes
- smooth fadeout of dimmer (was hard removing the dimmer without any transition on close)
- temp flyouts have to be put before pusher in dom to avoid auto pusher wrap when not necessary

### Sidebar fixes
- smooth fadeout of dimmer (was hard removing the dimmer without any transition on close)

### Sidebar features (adopted from modal)
- `blurring` setting

### modal fixes
- basic action on inverted dimmer

## Closes
#2457

### CODE REVIEW

**Comment by prudho** [comment]
When using non-exclusive flyout (ie. multiple flyouts) at the same time, closing one make the dimmer animating even when there's other flyouts. Is this a wanted behavior ?
Animation

**Comment by lubber-de** [comment]
> When using non-exclusive flyout (ie. multiple flyouts) at the same time, closing one make the dimmer animating even when there's other flyouts. Is this a wanted behavior ? 
I'll check that... There exists a `othersvisible` method, which should distinguish this

**Comment by lubber-de** [comment]
@prudho I fixed the dimmer animation on multiple flyouts (and sidebars) by 1ebf3a5d14ffa847d4c2fe12f9229a06092d5e75

**Review by prudho — APPROVED** [review]
Neat ! Everything look's fine 👍

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/373

**Pull request merged**
