### PR TITLE
[Build Tools] update to gulp4

### LINKED ISSUE #112: [Build Tools] update to gulp4
Merge this PR to update to gulp4 https://github.com/Semantic-Org/Semantic-UI/pull/6566

### PR DESCRIPTION
**Pull request by ColinFrick**
## Description
Update all dependencies with gulp 4
**Admin package was updated, but was not tested**

- [x] Verify css / js / assets build process (full / incremental)
- [x] Finish "watch" task
- [x] Test and finish "docs" tasks
- [x] Batch changes in "watch"
- [x] Handle deleted files (or skip)

## Closes
#112 / Semantic-Org/Semantic-UI#6549 / Semantic-Org/Semantic-UI#3793

### CODE REVIEW

**Comment by hammy2899** [comment]
Great work @ColinFrick, I will try and get some testing done in the next few days.

**Comment by hammy2899** [comment]
I just did some quick testing and found this error

```
Site folder exists, merging files (no overwrite) src/site/
[15:51:22] 'create install files' errored after 1.94 ms
[15:51:22] Error: ENOENT: no such file or directory, stat './src/_site'
    at Object.statSync (fs.js:829:3)
    at Object.exports.copyDirSyncRecursive (G:\fomantic\Fomantic-UI\node_modules\wrench-sui\lib\wrench.js:244:23)
    at G:\fomantic\Fomantic-UI\tasks\install.js:341:12
    at taskWrapper (G:\fomantic\Fomantic-UI\node_modules\undertaker\lib\set-task.js:13:15)
    at bound (domain.js:396:14)
    at runBound (domain.js:409:12)
    at asyncRunner (G:\fomantic\Fomantic-UI\node_modules\async-done\index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
[15:51:22] 'install' errored after 2.86 s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fomantic-ui@2.6.2 install: `gulp install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fomantic-ui@2.6.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Steps:

1. `npm install` then went through the installation process selecting all the default values
2. `rm -rf node_modules`
3. `npm install` this time it asked to extend my config and I selected Yes then Automatic.

**Comment by ColinFrick** [comment]
Weird because I didn’t really change install

**Comment by ColinFrick** [comment]
As I suspected this is a pre-existing problem. Just tested this on `master`
`gulp install` removes the _site directory, which other scripts are relying on.

How should we proceed with this problem? This should only affect users who clone the repository, and don't use fomantic-ui throughb npm.

**Comment by hammy2899** [comment]
Is there a way to check if `_site` exists before running the script and then showing a friendly error instead of the script crashing?

**Pull request merged**
