### PR TITLE
fix(font): patched lato 2.0 to fix positioning

### LINKED ISSUE #2529: [Input][Form] Everything is not Perfectly Align
# Bug Report
I found that in the new version, everything is not perfectly align, for example in this image:

Capture

Looks like everything seem to go up a bit.

I tried to use the FUI CSS old version (2.9.0-beta.163 or 2.9.0-beta.301+42e68bc), and everything perfectly align again. 
## Testcase
https://jsfiddle.net/KiddoV/x5tjgcLk/17/

## Version
2.9.0

### PR DESCRIPTION
**Pull request by lubber-de**
## Description

The new Lato 2.0 had a slightly changed positioning metrics, which i fixed via fontforge by using the same values as for lato 1

## Screenshots
Take a look at the Text positioning inside the black labels

|Broken|Fixed|
|-|-|
|image|image|

### Broken
https://jsfiddle.net/lubber/4Lzbma19/2
### Fixed
https://jsfiddle.net/lubber/4Lzbma19/11/

## Closes
#2529

### CODE REVIEW

**Review by KiddoV — APPROVED** [review]
Tested. Looking good now. Thanks!

**Comment by mvorisek** [comment]
we should not fork/update font sources if absolutely not needed - isn't this possible to fix via CSS?

**Comment by lubber-de** [comment]
The metrics for positioning were definitely wrong. Try text-decoration:Overline.
A css fix would have been needed on plenty of selectors and would have broken lots of other components.

**Comment by mvorisek** [comment]
@juliotrigo you are the author of Lato fonts, can you please comment on this issue?

**Comment by juliotrigo** [comment]
@mvorisek I'm not the author of Lato fonts so I'm afraid I can't really comment on this.
I've just been using the font and wrote an article about how I'm using it.

**Pull request merged**
