### PR TITLE
[Item] Inverted Variant

### LINKED ISSUE #109: [Item] add inverted variation
Add an inverted variation of item.

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
Inverted variant of Item.

## Screenshot
image

## Closes
#109

### CODE REVIEW

**Comment by lubber-de** [comment]
So I am removing inverteditemsbackground (which is currently set to black) only then. Because for items, extra and content there already was a background setting in the non inverted variant aswell, but set to transparent or none(as already discussed in the related issue)

**Comment by lubber-de** [comment]
@hammy2899 i removed the black background, so it's up to the user now to set it accordingly. 
I currently kept the inverted background settings for  item, content and extra (missed `inverted` anyway in the commits before) as they are set to the same value (transparent or none) as the normal item

If i should remove those aswell, then just tell me :slightly_smiling_face:

**Comment by hammy2899** [comment]
Maybe we should look into why the background is set by the item before we move forward. If it turns out it isn't for any reason maybe we should just not set it.

**Comment by lubber-de** [comment]
The latest commit supports texts directly in the `.content` element (normal or inverted) when used in `.items` or in `.list` aswell. Fixes https://github.com/Semantic-Org/Semantic-UI/issues/6652

Regarding the background: Also in `.list` it seems every background setting was just prepared for someone to be able to change the background via less variables. That said also for `.list` the background- (and inverted-background) defaults are again always either transparent or none,

While reading through the code of all other elements/modules i could not see any other reason, why item _needs_ to set the background (it was not even `!important`). So for backward compatibility we should not remove it.

So i think we should follow that for item alone too.

**Pull request merged**
