### PR TITLE
[menu] Dropdown inside menu should not reflect menu styling.

### PR DESCRIPTION
**Pull request by exoego**
## Description
Dropdown item inside `.pointing.menu` or `.secondary.pointing.menu` should not reflect menu item styling.

## Testcase
https://jsfiddle.net/bjup1fd5/

### 🐛 Pointing (Before)
pointing-before

### 🌟 Pointing (After)
image

### 🐛 Secondary Pointing (Before)
secondary-pointing-before

### 🌟 Secondary Pointing (After)
secondary-pointing-after

## Closes
https://github.com/Semantic-Org/Semantic-UI/issues/6463

### CODE REVIEW

**Comment by lubber-de** [comment]
Shouldn't the pointing arrow itself be hidden in the dropdown aswell instead of only the border on the first example?

**Comment by prudho** [comment]
Oh yeah I didn't saw that !

**Comment by exoego** [comment]
- [ ] Remove pointing arrow

**Comment by exoego** [comment]
Nice catch!
Removed pointer arrow in dropdown & updated screenshot.

**Comment by lubber-de** [comment]
> Removed pointer arrow in dropdown & updated screenshot.

Please push the related commit aswell :slightly_smiling_face:

**Pull request merged**
