### PR TITLE
chore(ci): Add job to enforce commit message convention

### PR DESCRIPTION
**Pull request by aexvir**
## Description

Seeing that fomantic ui requests following the Angular git commit message convention, which is precisely what was used as base for the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) proposal, I wanted to suggest using a CI tool for making sure that the commits follow the convention.

`commitsar` is a small go binary that does just that, I personally know and work with the developer, I don't think it matters but I just don't want to hide it. I think it could be a good and lightweight solution for https://github.com/fomantic/Fomantic-UI/issues/341

### CODE REVIEW

**Comment by hammy2899** [comment]
We had something like this in the past and like you mentioned this issue https://github.com/fomantic/Fomantic-UI/issues/341 was created. I don't think we need to lint commit messages because it adds confusion to outside contributors and to be honest we don't care the format of a commit message because we will just format it correctly when we merge it.

That being said I think we should just leave this to make contributing easy for any new contributors.

@fomantic/core whats your 2 cents?

**Comment by lubber-de** [comment]
I agree with @hammy2899

**Comment by aexvir** [comment]
Actually, thanks to this PR we found some small issue in the branch targeted on GitHub actions. Fixed now 🙂

**Comment by hammy2899** [comment]
I'm going to close this because the last time we had something like this it caused a few issues with some people and I don't want to increase the complexity for new contributors.

@aexvir This is a good PR however as I said above this does add confusion for new contributors and we can't afford that in the current state of FUI. (maybe for v3 😉)

**Pull request closed without merging**
