### PR TITLE
[Build] Refactor dependencies

### PR DESCRIPTION
**Pull request by hammy2899**
## Description

Refactor dependencies so they are in the correct place and so they all have specific versions instead of `*` and remove the unless peerDeps. Also update a few dependencies.

## Related
#386

### CODE REVIEW

**Comment by lubber-de** [comment]
I think `package-lock.json` has to be regenerated also. Travis [does not build](https://travis-ci.org/fomantic/Fomantic-UI/builds/495876844?utm_source=github_status&utm_medium=notification) (i already tried to restart the build, but still not building) and i remember, we had a similar situation before while dealing with the Event stream issue #269

**Comment by lubber-de** [comment]
@hammy2899 
🤔 I see now, `package-lock.json` is already part of your PR... any idea, why travis does not work then?

**Comment by lubber-de** [comment]
Perhaps, because you added `dev:true`  to the dependencies, but travis.yml has set "production"?
https://github.com/fomantic/Fomantic-UI/blob/783786b5c27bf0252dc47c0277746b4a695210ca/.travis.yml#L18

**Comment by hammy2899** [comment]
@lubber-de Yeah, I will change the env and see if that fixes it

**Comment by hammy2899** [comment]
@lubber-de Fixed 👍

**Pull request merged**
