### PR TITLE
fix(checkbox): remove the change trigger for enable and disable behavior

### PR DESCRIPTION
**Pull request by prudho**
As discussed in #1728, triggering the `onChange` callback in the `enable` and `disable` behaviors is useless so I've just removed it.

Other question is: should we consider this as a breaking change and wait 2.9 to release it ?

### CODE REVIEW

**Comment by lubber-de** [comment]
If some existing projects relies on the onchange event when enabling/disabling  a checkbox this should be considered a breaking change, IMHO, yes.
Let' vote 😄

**Review by lubber-de — APPROVED** [review]
LGTM

**Review by ko2in — APPROVED** [review]
LGTM. I also think it should be a breaking change.

**Review by exoego — APPROVED** [review]
LGTM

> https://github.com/fomantic/Fomantic-UI/discussions/1728#discussioncomment-113240
> `onchange` should IMHO only be called when the check state changes. Even, if you disable a checked checkbox, it will still be checked (thus: did not change)

This sounds reasonable to me.

**Pull request merged**
