### PR TITLE
[Dropdown] Multiple search button dropdown misaligned, placeholder wraps and search text ghosting

### LINKED ISSUE #1623: [dropdown] when multiple, placeholder text is wrapped
# Bug Report
When using a dropdown with multiple selection, placeholder text with spaces is wrapped. It's not when removing the multiple part.

## Steps to reproduce

cf. jsfiddle

## Expected result
text should not be wrapped in multiple like the no multiple dropdown

## Actual result
text is wrapped

## Testcase
This is the test case for latest version of fomantic (2.8.6) https://jsfiddle.net/jLn0wkv9/1/
Also we notice some kind of change between the 2.8.4 and 2.8.5 of this kind of input (but still with the wrap text issue) here the jsfiddle with 2.8.4 https://jsfiddle.net/1yxtrqen/1/

## Screenshot (if possible)
2.8.6 (multiple is on right)
image
2.8.4 (multiple is on right)
image

## Version

2.8.6

## Notes
For the change between 2.8.4 and 2.8.6 its a css rule that override the padding of multiple dropdown
2.8.4:
image

2.8.6:
image

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
This PR fixes

- multiple search button dropdown had wrong padding
- Placeholders in multiple search dropdowns were wrapping
- Search in dropdown buttons had ghosting text

## Broken
https://jsfiddle.net/lubber/47r2v1cf/59

## Fixed
https://jsfiddle.net/lubber/47r2v1cf/60

### Broken
multipleghost

## Fixed
multiplenoghost

## Closes
#1623

### CODE REVIEW

**Review by ko2in — COMMENTED** [review]
The default value for `min-width` of `.ui.search.dropdown` is empty which is invalid.
Dropdown

https://github.com/fomantic/Fomantic-UI/blob/df26dde8e64674a497f6ac61e5962d9f4a1a5680/src/themes/default/modules/dropdown.variables#L222

I think we should use the same min-width value as `@selectionMinWidth`.
https://github.com/fomantic/Fomantic-UI/blob/df26dde8e64674a497f6ac61e5962d9f4a1a5680/src/themes/default/modules/dropdown.variables#L131

Or I suggest `min-content` as default value. What do you think?

**Comment by ko2in** [comment]
As far as I tested, all produce the awkward results apart from the unit value.
### min-width: auto | fit-content | initial | max-content | min-content | revert | unset
min-width-1

### min-width: inherit
min-width-2

### min-width: moz-available | -webkit-fill-available
min-width-3

I guess it should use the same unit as `@selectionMinWidth` then.

**Comment by lubber-de** [comment]
@ko2in No, we should not change this (and it's not even part of this PR 😉 )

If you set a fixed value for `.ui.search.dropdown` all code which is using this inline will break because it's getting much wider than probably desired

See the last dropdown in this jsfiddle https://jsfiddle.net/lubber/47r2v1cf/67/
### Current
image

### Your proposed change
image

**Comment by lubber-de** [comment]
@ko2in And `min-content` will also reduce the existing selection dropdown width
image

**Comment by lubber-de** [comment]
Lets discuss / maybe adjust this in a separate PR

**Review by ko2in — APPROVED** [review]
LGTM. I've already created an [issue](https://github.com/fomantic/Fomantic-UI/issues/1657) for the invalid CSS syntax, where we can discuss for that.

**Review by prudho — APPROVED** [review]
LGTM

**Pull request merged**
