### PR TITLE
[Header] Icon content was not aligned

### LINKED ISSUE #1708: "center aligned icon header" miss aligned using "content"
# Bug Report
From v2.7.5 to v2.8.7 something got broken with "center aligned icon header" that miss aligned the "content" class.

## Steps to reproduce
1. Please see the JSFiddle
2. Removing the &lt;div class="content"&gt; work around the issue
3. Re-adding CSS .ui.icon.header .content { display: block; } works too

Seems like the CSS order changed from 2.7 to 2.8

## Expected result
Center aligned content (using a "content" class)

## Actual result
Left aligned content

## Testcase
https://jsfiddle.net/sLnaf9yg/

## Version
2.8.7

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
The specificity has changed for icons by #1593 . This had an impact when using an `aligned icon header` to not correctly be aligned anymore because of the wrong display setting.
This PR adjusts the specificity again

## Testcase
https://jsfiddle.net/lubber/j294u6mx/7/

### Broken
image

### Fixed
image

## Closes
#1708

### CODE REVIEW

**Review by exoego — APPROVED** [review]
LGTM

**Review by prudho — APPROVED** [review]
LGTM

**Review by ko2in — COMMENTED** [review]
Is it possible to remove `display: table-cell` from `.ui.header > i.icon + .content`? I've tested with this fiddle (https://jsfiddle.net/ko2in/jh62gstx/) and it doesn't break anything.

FUI

I usually prefer to avoid unnecessary overrides as much as possible.

**Comment by lubber-de** [comment]
@ko2in The override is necessary, because the `block` is the previous behavior even in SUI
When removing the `table-cell` it will break non aligned icon headers 
See
breakingtablecell

**Comment by ko2in** [comment]
@lubber-de I see. Then I think it's better to omit for center header instead of overrides like:
```
.ui.header:not(.center) > i.icon + .content {
  padding-left: .75rem;
  display: table-cell;
  vertical-align: middle;
}
```
It looks more semantic to me. And it wouldn't have unnecessary left padding too for center icon header. I've tested with this [page](https://fomantic-ui.com/elements/header.html) and it works well.

**Comment by lubber-de** [comment]
@ko2in Agreed. Nice catch 👍 
However, i had to change your suggestion to `:not(.centered):not(.aligned)` because otherwise `right aligned` as well as `centered` would not work anymore (there exists an alias `centered` for `center aligned`, that's why).
I adjusted the PR accordingly and reverted the specificity change, please review again @prudho  @exoego

**Review by exoego — APPROVED** [review]
LGTM

**Review by ko2in — APPROVED** [review]
LGTM.

**Pull request merged**
