### PR TITLE
[Calendar] Fire onchange only when date selection is complete

### PR DESCRIPTION
**Pull request by prudho**
## Description
This PR allow to fire `onChange` only when a date selection if complete. For a datetime for example, onChange is called when a date is selected, then when a hour is selected, and again when minutes are selected... which is IMHO is a complete nonsense. If I apply a method when a date is changed, i'd prefer trigger this change only when i have finished to select my date...

Note 1: This may be labelled as a breaking change.

Note 2: This PR also include a small "refactor" of variables declarations I planned to publish later. As you know my git skills are legendary so revert this is really a PITA for me. As it's only minimal style change, do you mind if we let this PR as it ?

## Testcase
Select a date, then a time and then a hour.

Before: [JSFiddle](https://jsfiddle.net/cxb4ogzn/)
After: [JSFiddle](https://jsfiddle.net/cxb4ogzn/1/)

### CODE REVIEW

**Comment by lubber-de** [comment]
@fomantic/maintainers Should we merge this into 2.8.4 now or postpone to 2.9 because of the possible breaking change consideration prudho mentioned? Your thoughts?

**Comment by prudho** [comment]
I'm pretty mixed about releasing it with 2.8.4, since I have another incoming PR which will be a breaking change, and I think both of them will need heavy tests to be sure there's no hidden bug (date setting logic is pretty much rewritten).

**Comment by lubber-de** [comment]
So then postpone this for 2.9.  Especially when you will provide another PR later on :)

**Comment by lubber-de** [comment]
> I'm pretty mixed about releasing it with 2.8.4, since I have another incoming PR which will be a breaking change, and I think both of them will need heavy tests to be sure there's no hidden bug (date setting logic is pretty much rewritten).

@prudho Do you still work on that mentioned PR?

**Comment by prudho** [comment]
@lubber-de no. As you've seen it i'm not really active during this strange days. I think this PR can be merged if you want to.

**Comment by lubber-de** [comment]
Then i tag this for 2.8.5, because it's really more a bugfix than a feature, IMHO

**Pull request merged**
