### PR TITLE
feat(chore): enable codeql action

### PR DESCRIPTION
**Pull request by naveensrinivasan**
This action runs GitHub's industry-leading semantic code analysis engine, CodeQL, against a repository's source code to find security vulnerabilities.

https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

https://github.com/ossf/scorecard/blob/main/docs/checks.md#sast

### CODE REVIEW

**Comment by lubber-de** [comment]
Thanks, this is great. However, we will first take a look at all the findings from this PR before merging this.

**Comment by naveensrinivasan** [comment]
> Thanks, this is great. However, we will first take a look at all the findings from this PR before merging this.

Sounds good.

**Comment by exoego** [comment]
Opened a PR to address one of issue in CodeQL result. https://github.com/fomantic/Fomantic-UI/pull/2358

**Comment by naveensrinivasan** [comment]
> Opened a PR to address one of issue in CodeQL result. #2358
> I think all other "Cricitcal" issues (incomplete replace) can be dismissed.

I have merged it.

**Review by lubber-de — CHANGES_REQUESTED** [review]
Please adjust the codeql.yml so it does not scan the `/dist` folder.
That folder is only updated upon a release, so when we prepare a PR to fix the mentioned issues, those won't be updated inside the /dist folder.

Alternatively include the CI steps which will build the /dist folder before running codesql

**Comment by naveensrinivasan** [comment]
> Please adjust the codeql.yml so it does not scan the `/dist` folder. That folder is only updated upon a release, so when we prepare a PR to fix the mentioned issues, those won't be updated inside the /dist folder.
> 
> Alternatively include the CI steps which will build the /dist folder before running codeql

Took care of it! PTAL.

**Comment by lubber-de** [comment]
The findings should have been fixed by #2375. Please merge the current develop branch.
2 issues are false positives, i'll mark them accordingly after merging.

**Comment by naveensrinivasan** [comment]
> The findings should have been fixed by #2375. Please merge the current develop branch.
> 2 issues are false positives, i'll mark them accordingly after merging.

I have merged the develop branch. PTAL. Thanks

**Review by lubber-de — APPROVED** [review]
LGTM 👍🏼

**Pull request merged**
