### PR TITLE
fix(dropdown): fix menu item text breaking issue

### LINKED ISSUE #1820: Overlapping UI elements
# Bug Report
The attached image should describe the issue pretty well.

## Steps to reproduce
1. Give a long option in a Dropdown
2. Minimize the viewing area.

## Screenshot (if possible)

image

### PR DESCRIPTION
**Pull request by ko2in**
## Description
When the menu item contains too long text, the text doesn't break into the new line when there's no enough space to display in
single line and the text overflows the container.

Even though the text can be forced to break using `break-word: break-all`, it doesn't look good enough when there is an image representing next to the menu text.

menu

This PR fixes the menu item text breaking problem and also changes the container to flexbox to render the image, text, and the dropdown icon as flexbox items to align better.

Since the menu item has changed to the flexbox model and the dropdown icon and direct children elements of a menu item are appearing as flex items and the float property has no effect on flexbox, and so the float rules and variables for the dropdown icon are removed by this PR.

## Testcase
**Bug:** https://jsfiddle.net/ko2in/3sw01eLz/1/

**Fixed:** https://jsfiddle.net/ko2in/3sw01eLz/9/

## Screenshot
**Before:**
menu-bug

**After:**
menu-fix

## Closes
#1820

### CODE REVIEW

**Review by lubber-de — CHANGES_REQUESTED** [review]
This unfortunately breaks 2 usecases i found

- Floating Content https://fomantic-ui.com/modules/dropdown.html#floated-content
- Short menu items (dropdown icon for submenu not to the very right anymore if other menu items are longer)

## Testcase
### Normal
https://jsfiddle.net/lubber/9yu8wr3v/12/
### Your PR
https://jsfiddle.net/lubber/9yu8wr3v/14/

## Screenshots
### Normal
1838normal

### Your PR
1838broken

**Comment by ko2in** [comment]
@lubber-de I've fixed the floated icon issues. Please review again. I've updated the fiddle link (New link: https://jsfiddle.net/ko2in/3sw01eLz/7/) in my description.

There is also a left floated icon which has the right margin `1em`, but a default icon without `left floated` has the right margin `.78571429rem`. I'm not sure why do they have two different values for margin. I think the `left floated` variant is not required since it's basically the default style.

**Comment by ko2in** [comment]
@lubber-de I found a minor issue with icon alignment and description left-margin and fixed it. Here's the fiddle link (https://jsfiddle.net/ko2in/3sw01eLz/9/). You can compare with the previous version (https://jsfiddle.net/ko2in/3sw01eLz/7/).

**Comment by lubber-de** [comment]
Wow, this looks much better, i am still testing, but it seems you also fixed #1071 by 99%. 👍 
Look a this jsfiddle https://jsfiddle.net/lubber/af71eLmr/5/
When running in IE11 / Edge 12 or Safari 12.1/13.1 the submenu arrow for "Submenu 2" is still misaligned while "Submenu 3" is fine now by your PR!)
image
Do you think you can fix this as well? (Don't worry, if not, i will still approve this PR, as it is much better overall with the flex settings and fixes the original issue and keeps everythins else intact as before!)
We can also address this separately if ou dont want to touch this PR anymore, while it's stable

**Review by lubber-de — CHANGES_REQUESTED** [review]
Basically LGTM 👍 
Very good job!
Please change the little specifity as shown and remove the !important and use a doubled `.ui` instead (for both `right floated` selectors)

**Comment by ko2in** [comment]
@lubber-de Please hold for the PR for a moment. I also find some problems with the upward direction menu. I'll look into it and also your issue above and update the PR.

**Comment by lubber-de** [comment]
@ko2in Did you find a solution for your found upward directon issue? (i didnt came across that, so maybe you can share a jsfiddle to show what's wrong with your PR?)

You dont necessarily have to also fix the arrow icon i mentioned [here](https://github.com/fomantic/Fomantic-UI/pull/1838#issuecomment-758092650) because that'c basicaly not related to your PR / issue

**Comment by ko2in** [comment]
@lubber-de I did find out the solution for the upward direction menu. But, changing to the flexbox model reflects also some parts which I'm trying to fix. The vertical sidebar menu and accordion inside the menu are also affected by this change. I've fixed almost every issue I've found.

The icon issue you mentioned [here](https://github.com/fomantic/Fomantic-UI/pull/1838#issuecomment-758092650) doesn't relate to my PR. But, the icon positions are also affected too especially the left and right position and their margins which I'm trying to fix now. The margin inside the flexbox is really a challenge though.

I'll submit the updated PR this weekend if I didn't find anything else with my changes.

**Comment by lubber-de** [comment]
@ko2in If you still have issues to solve, please convert this PR into Draft

**Review by lubber-de — CHANGES_REQUESTED** [review]
Please revert the dist folder changes. They should not be part of the PR

**Comment by ko2in** [comment]
> Please revert the dist folder changes. They should not be part of the PR

These might have received when [merging](https://github.com/fomantic/Fomantic-UI/pull/1838/commits/fcf419980518157d1193ea84b044eee10f1abffb) develop branch into my branch. :thinking:

**Comment by ko2in** [comment]
> > > Please revert the dist folder changes. They should not be part of the PR
> > 
> > 
> > These might have received when [merging](https://github.com/fomantic/Fomantic-UI/pull/1838/commits/fcf419980518157d1193ea84b044eee10f1abffb) develop branch into my branch. thinking
> 
> Try to rebase, because if the develop branch would have been merged there would not be any changes

@lubber-de I've done rebasing, but I am not able to push to this branch anymore. So, I created another [PR](https://github.com/fomantic/Fomantic-UI/pull/2804). I'm closing this PR.

**Pull request closed without merging**
