### PR TITLE
[Toast] horizontal variant and dynamic DOM node content support

### LINKED ISSUE #1370: Toast is not semantic
Hi!
Have been using Semantic UI for a long time and i love it and ofcourse this fork. 
But unfortunately i have to notice that the main idea of Semantic UI (yes, it is semantic ui) is not implemented by Toast component. I'd like to suggest to minimize amount of JavaScript and maximize of semantic html.
Best wishes.

### PR DESCRIPTION
**Pull request by lubber-de**
## Decription
This PR adds 

- the `horizontal` variant
- dynamic setting of title, message, icon or image to a toast template create out of an existing DOM node
- makes the close duration time configurable just as it is possible for show/hide duration

to the `toast` module.

## Testcase
The testcase uses DOM Node templates without content as  a base to create the toast and changes its content by the usual settings and makes use of the new `horizontal` variant.
https://jsfiddle.net/lubber/Lsrg071y/45/

## Screenshot
dynamichorizontaltoast

## Closes
#1370

### CODE REVIEW

**Review by prudho — APPROVED** [review]
Nice ! LGTM 👍

**Review by ko2in — APPROVED** [review]
LGTM.

**Review by exoego — APPROVED** [review]
LGTM 🏅

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/255

**Pull request merged**
