### PR TITLE
fix(step): unnecessary semicolon breaks webpack build

### LINKED ISSUE #2027: ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf;charset=utf-8;;
# Bug Report
Webpack module build failed because of the extra semicolon in `Line 41024` in node_modules\fomantic-ui-css\semantic.css

## Steps to reproduce

1. Upgrade to webpack 5.x.x, mini-css-extract-plugin 2.x.x, and fomantic-ui-css 2.x.x
2. Use webpack 5 asset modules => https://webpack.js.org/guides/asset-modules/
3. My webpack.config =>
```js
plugins: [
    new MiniCssExtractPlugin({
        filename: "[name].css"
    })
],

module: {
    rules: [
        {
             test: /\.js?$/,
             exclude: /node_modules/,
             loader: "babel-loader"
        },
        {
             test: /\.css$/i,
             use: [
                 MiniCssExtractPlugin.loader,
                 "css-loader"
             ]
        },
        {
             test: /\.(png|svg|jpg|jpeg|gif)$/i,
             type: "asset/resource"
        },
        {
             test: /\.(woff|woff2|eot|ttf|otf)$/i,
             type: "asset/resource"
        }
    ]
}
```

## Expected result
Webpack compilation without errors.

## Actual result
**ModuleBuildError: Module build failed: UnhandledSchemeError: Reading from "data:application/x-font-ttf;charset=utf-8;;base64**

## Screenshot (if possible)
image

## Version
fomantic-ui-css v2.8.8
webpack v5.46.0
mini-css-extract-plugin v2.1.0

### PR DESCRIPTION
**Pull request by lubber-de**
## Description

A typo breaks usage of webpack. Caused by a double semicolon in a font face description (which is tolerated by browsers)

## Testcase
See #2027 

## Closes
#2027

### CODE REVIEW

**Review by exoego — APPROVED** [review]

**Comment by hwinkler** [comment]
It's be awesome to get this fix into a release to npm.

**Comment by georgkrause** [comment]
@lubber-de Any chance this can be released as a patch?

**Comment by lszmit-nm** [comment]
@lubber-de @hammy2899 Could this also be applied to the less package? It's still based on 2.8.8 and experience the same issue with webpack5. Thank you.

**Comment by parneetski** [comment]
@lubber-de Can we get an update on when this will be merged into the main repo (and subsequently the -css distribution)?

**Pull request merged**
