### PR TITLE
Checkbox fields

### LINKED ISSUE #578: Add padding to checkbox input when necessary inside form fields
# Feature Request

## Description
Sometimes I like to have checkboxes inside `.ui.form>.fields>.field` layouts, but currently it has no padding and puts the checkbox at the top of the field. I think it should pad the checkbox's top so it lines up with the inputs better.

## Example
I used the following CSS to make it look better:
```css
.ui.form .fields .field:not(:only-child) .ui.checkbox {
  margin-top: 2.25em;
}
.ui.form .fields .field:not(:only-child) .ui.toggle.checkbox {
  margin-top: 2.15em;
}
.ui.form .fields .field:not(:only-child) .ui.slider.checkbox {
  margin-top: 1.35em;
}
```

The `:not(:only-child)` selector ensures that the checkbox will not have the extra padding if it is the only `field` in the `fields` div.

## Testcase
https://jsfiddle.net/bha06ugz/

## Screenshot
image

### PR DESCRIPTION
**Pull request by GammaGames**
## Description
Adds padding to checkboxes inside fields so that they line up vertically with input fields

## Testcase
https://jsfiddle.net/f3ysmtpg/

## Screenshot
image

## Closes
#578

### CODE REVIEW

**Comment by GammaGames** [comment]
Hmm, I didn't know there were commit types and I only ever use the command line and don't add messages. I can try and squash my commits later if it would make the bot happy

**Comment by hammy2899** [comment]
@GammaGames 

> Please commit using the AngularJS Git Commit Message Convention this is more of a nice to have and isn't required.
- https://github.com/fomantic/Fomantic-UI/blob/master/CONTRIBUTING.md

**Comment by GammaGames** [comment]
I set the margin variables to nicer numbers and did some math in the less file, let me know if that is inappropriate

**Comment by lubber-de** [comment]
@GammaGames LGTM now. Thanks for the nice PR

**Pull request merged**
