### PR TITLE
fix(cards): fix horizontal card actions being forced to the right.

### LINKED ISSUE #159: [Card] horizontal cards meta & actions are forced to the right
# Bug Report

## Steps to reproduce
1. create a horizontal card
2. add some meta data or a button

## Expected result
The meta data or button should appear under the card

## Actual result
The meta data or button is forced to the right

## Description

This is caused because of `flex-direction: row` when setting `flex-wrap: wrap` buttons then flow under the card but meta data will force the content to go under the image. If the content is too long it will also wrap to the next row.

## Testcase
https://jsfiddle.net/Lwxau2yn/

## Screenshot
image

## Version
2.6.2

### PR DESCRIPTION
**Pull request by tcmal**
fixes #159
## Testcase

Previous: https://jsfiddle.net/Lwxau2yn/
New: https://jsfiddle.net/tcmal/dys0khbx/

## Screenshot (when possible)

image

## Closes

#159

### CODE REVIEW

**Comment by hammy2899** [comment]
Using `flex-basis` is a good idea but it doesn't work for this https://jsfiddle.net/tcmal/dys0khbx/

**Comment by tcmal** [comment]
It displays fine for me, MDN says it should be well implemented.

**Comment by hammy2899** [comment]
This doesn't seem to work for me on Chrome or Firefox

image

https://jsfiddle.net/r3q2wco6/

Does anyone else have the problem?

**Comment by tcmal** [comment]
Works for me on firefox & chrome. What versions?

Does this work better? https://jsfiddle.net/tcmal/5sbjqkh6/

I had a typo so the flex-basis wasn't actually being applied. I also added it to top attached buttons for consistency.

**Comment by hammy2899** [comment]
No, that someone makes it worse, the image and content should be on the same row but meta data and buttons etc should be on another under the image and content.

**Comment by tcmal** [comment]
Does it work better [with a grid](https://jsfiddle.net/tcmal/rhfznovb/)? It seems like the width isn't being set high enough for you, presumably it's a display size thing.

**Pull request closed without merging**
