### PR TITLE
[Enhancement]: [Search] Scrollable search result

### PR DESCRIPTION
**Pull request by patilkiranm**
## Description

Now it is possible to make search results scroll-able. 
1. Handles keyboard events
2. Regains scroll position after closing of results due to blur/click event

## Screenshot 
Search: Without category
ScrollableSearch

Search: Withcategory
ScrollableSearch2

### CODE REVIEW

**Comment by exoego** [comment]
I tested this PR in http://jsfiddle.net/gtk760c3/2/ added by @lubber-de .
Scrolling is useful if search results contains tens of entries, but I think current height of scrollbale result is a bit shorter: it can only show 2-3 lines.
image

**Comment by patilkiranm** [comment]
@lubber-de Scrolling and height variations added to results :)

**Comment by lubber-de** [comment]
@patilkiranm Please see my comment from the docs PR https://github.com/fomantic/Fomantic-UI-Docs/pull/199#pullrequestreview-370189909, because the scrolling only has effect on mobile/small devices (or if the `maxResults` value is drastically increased

**Comment by lubber-de** [comment]
@all-contributors please add @patilkiranm for code and doc

**Pull request merged**
