### PR TITLE
[Rating] Fix unworking `fireOnInit`

### PR DESCRIPTION
**Pull request by prudho**
## Description
Basically the same as #1006, but done after a coffee and brain usage...

### CODE REVIEW

**Comment by exoego** [comment]
> #1006
> But all the initialLoad logic is actually useless, so why not clean the code instead 

So, is this line wrong ?

**Comment by prudho** [comment]
@exoego yes, it's wrong. Actually the code can be (very) simplified, but we must keep this flag.

**Comment by prudho** [comment]
@hammy2899 please wait a little before merging it, my next PR will show how i can improve the code.

**Comment by prudho** [comment]
Please take a look at my PR #1008. Do you want it to be simplified like that ?

**Comment by hammy2899** [comment]
@prudho Should just close this and use the other PR.

**Comment by prudho** [comment]
Sure ! Will do.

**Comment by ColinFrick** [comment]
@prudho so this PR should be closed right?

**Pull request closed without merging**
