### PR TITLE
[Flag] Added catalan flag

### PR DESCRIPTION
**Pull request by TheJltres**
## Description
Added Catalan flag.
In theory there's other flag, but I can't see it.

## Testcase
https://jsfiddle.net/TheJltres/9bxmc7rq/1/

## Closes
https://github.com/Semantic-Org/Semantic-UI/issues/6926

Is the correct folder? :roll_eyes:

### CODE REVIEW

**Comment by ColinFrick** [comment]
Thanks for the PR. This looks fine to me, but we'll replace the current sprite-based flag with a new system in 2.9 #1190
So I'm unsure if we'll merge it now @fomantic/maintainers

**Comment by lubber-de** [comment]
@TheJltres  Although your PR is technically valid, there does not exist either an official country code nor an existing unicode for the catalonian flag. That said it's not officially supported by any emoji provider.

I don't want to have politial discussion here, but if we merge this now, the flag won't appear in 2.9 anymore until it gets an offical country code or is at least supported by the official unicode list for country flags or subdivision flags, so that tweemoji, joypixels and others are supporting it.
https://unicode.org/emoji/charts/full-emoji-list.html#country-flag

**Comment by TheJltres** [comment]
It's okey, as you saw now if you want you can add like I answered in semantic issue

**Comment by lubber-de** [comment]
Closing, because of the above mentioned reasons we will not merge this. @TheJltres also agreed to this decision via discord
If somebody still needs this vor the 2.8.x branch, just add the 3 LOC from this PR to your own code

**Pull request closed without merging**
