### PR TITLE
[build] fix the minified css build

### LINKED ISSUE #1356: CSS Build randomly omits 34kB of output
Running the `gulp build` task seems to randomly omit around 34kB of CSS output in `semantic.min.css` related to the `Transition` module which in turn leads to `Transition: Element is no longer attached to DOM` JS errors when using that build.

To reproduce, clone the master branch, `npm install`, answer all choices with default and run:

````
while true; do rm -rf dist && npm run build &>/dev/null && stat --printf="%s" dist/semantic.min.css | xargs; done
````

It will randomly produce less CSS output, around 30% of times in my sample runs:
````
1354924
1354924
1321417
1354924
1354924
1321417
1321417
1354924
1354924
1354924
1354924
1354924
1354924
1354924
1321417
1321417
1321417
1321417
1354924
````

I see this on Node.js 12.16.1 and 13.10.1 on Linux. Adding `--series` to the `gulp` arguments does not seem to have any affect.

### PR DESCRIPTION
**Pull request by das7pad**
## Description

Wait for the uncompressed build to complete before gathering .css files
 for the packed .min.css file.

## Testcase

Rebuild the css multiple times, eventually the race condition is hit.

```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
```

## Screenshot (if possible)

```
# for reference
$ node -v
v12.16.1
```
#### before
```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
1354660
1354660
1354660
1321153
^C
```

#### after
```
$ while true; do rm -rf dist/* && npx gulp build-css &>/dev/null && stat --printf="%s\n" dist/semantic.min.css; done
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
1354660
^C
```

## Closes

Closes #1356

### Who needs to know
cc @silverwind

### CODE REVIEW

**Comment by das7pad** [comment]
> Can `packCompressed` start before `buildUncompressed` ?

No, the execution branches like this:
```
|-- buildCompressed
`-- buildUncompressed
    |-- packCompressed
    `-- packUncompressed 
```
See the docs https://gulpjs.com/docs/en/api/series -- especially the example at the bottom, `clean` runs before either of the two `css`/`javascript` tasks run.

**Comment by silverwind** [comment]
Thanks, this does appear to fix the issue for me, I did 20 builds and all were good.

**Comment by silverwind** [comment]
There is a somewhat similar `gulp.parallel` [in the js build](https://github.com/fomantic/Fomantic-UI/blob/62bd67026d8fb3bb64df935f9165f13927d8c786/tasks/build/javascript.js#L112), but I think it's not affected as it only parralelizes the `pack` operations.

**Comment by lubber-de** [comment]
@all-contributors please add @das7pad for code

**Pull request merged**
