### PR TITLE
[Calendar]: Inverted Variant

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
This PR adds full `inverted` support to the calendar component.
It also adds new metadata support for disabled/eventDates to supply new attributes `inverted` and `variation`. This way each cell tooltip can be adjusted on its own and makes it possible to have inverted or `basic` cell tooltips on non inverted calendars and vice versa

## Testcase
https://jsfiddle.net/lubber/xo2b9tfz/19/

## Screenshots
- `inverted calendar`
image

> The darker left pointer or the calendar surrounding popup isn't part of this PR, because it's a general issue also for normal calendar and covered in #1084 

- ... keep non inverted cell tooltip
```javascript
disabledDates: [{
  date: new Date(2020, 11, 19),
  message: 'xmas gift shopping',
  inverted: false
}],
```
image
- ... normal calendar, but inverted tooltip
```javascript
disabledDates: [{
  date: new Date(2020, 11, 19),
  message: 'xmas gift shopping',
  inverted: true
}],
```
image

- ... tooltip variation
```javascript
disabledDates: [{
  date: new Date(2020, 11, 19),
  message: 'xmas gift shopping',
  variation: 'basic'  // = no pointer as of docs
}],
```
image
image

### CODE REVIEW

**Comment by exoego** [comment]
image
Arrow seems too dark ?

**Comment by lubber-de** [comment]
> image
> Arrow seems too dark ?

@exoego  Yes, i already mentioned this in the PR description :wink:
> The darker left pointer or the calendar surrounding popup isn't part of this PR, because it's a general issue also for normal calendar and covered in #1084

**Comment by lubber-de** [comment]
Please review again, i solved merge conflicts and fixed tooltip flickering on inverted disabled cells
https://jsfiddle.net/lubber/xo2b9tfz/19/

**Comment by lubber-de** [comment]
Docs added by https://github.com/fomantic/Fomantic-UI-Docs/pull/222

**Pull request merged**
