### PR TITLE
feat(dependency): support a possible installed v4 of less

### LINKED ISSUE #1893: [build] LESS 4 is not supported by gulp-less->accord dependency
# Bug Report
Error less in build to laravel 8 (phpstorm ide)

## Steps to reproduce
1. npm install fomantic-ui
2. cd node_modules/fomantic-ui
3. gulp install

## Expected result
setup gulp

## Actual result
Error: less version 4.1.1 is not currently supported

## Version
last

The error is not clear why he swears at less which is in the root of the project, if the fomantic-ui folder has its own npm environment. There is less 3.7.0 in the modules inside the fomantic-ui folder.
And in the root of the project in node_modules less 4.1.1
How to be? How to build fomantic and why is it throwing an error?

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
We fixed support for LESS 4 by #1819 , but the package.json retricts installation to 3.x if less 4.x is already installed by throwing "this version is not supported". Seems more and more people have LESS 4 installed now which breaks installation in some setup environments 

I changed the dependency so every version >= 3.7 is supported now

## Related
#1893

### CODE REVIEW

**Comment by lubber-de** [comment]
Although this PR supports a higher major version of LESS, this will not help getting fomantic-ui installed with less 4.x installed, because the latest version of `gulp-less` still only supports less 3, so we are stuck until gulp-less changes its dependencies itself 😯

**Comment by lubber-de** [comment]
Related gulp-less support for less 4 at https://github.com/gulp-community/gulp-less/issues/312

**Comment by lubber-de** [comment]
The upcoming gulp-less PR https://github.com/gulp-community/gulp-less/pull/313 will support LESS 4 by removing the unmaintained accord dependency. 
I know changed the less dependency accordingly

**Review by exoego — APPROVED** [review]
LGTM

> https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies
> `range1 || range2~ Passes if either range1 or range2 are satisfied.

**Review by prudho — APPROVED** [review]

**Comment by lubber-de** [comment]
I merge this, so we and dependabot are prepared once gulp-less releases their next version

**Pull request merged**
