### PR TITLE
Fix vertical pointing menu

### PR DESCRIPTION
**Pull request by grandeljay**
When you are using a pointing menu and it stacks, due to small screen size, the pointer should disappear. 

Unfortunately I have no experience with CSS preprocessors (yet), so I'll likely need some help for any changes.

image

https://jsfiddle.net/gLhb4um3/

### CODE REVIEW

**Comment by grandeljay** [comment]
But isn't it always desired for a `fluid` pointing menu?

If it is fluid, there's nothing next to it. So IMO it's save to remove the pointer and your suggested code above would work great.

**Comment by grandeljay** [comment]
And if there was something next to it (like another column) it would be underneath the menu anyway (due to the `.stackable` class)

**Review by lubber-de — CHANGES_REQUESTED** [review]
Ok, convinced 🙂 

Please change it as follows:

- add the selector after the last selector inside the `  & when (@variationMenuVertical) {` scope
- make the selector dependant on enabled stackable grid and enabled fluid menu
- also do the same fix for `stackable pointing menu` see https://jsfiddle.net/lubber/rya73wz2/14/

So it becomes
```less
  & when (@variationMenuVertical) {
    .ui.vertical.pointing.menu .active.item:hover::after {
      background-color: @arrowVerticalHoverColor;
    }
    .ui.vertical.pointing.menu .active.item::after {
      background-color: @arrowVerticalActiveColor;
    }
    .ui.vertical.pointing.menu .menu .active.item::after {
      background-color: @arrowVerticalSubMenuColor;
    }
    // here your addition starts -->
    & when (@variationMenuFluid) and (@variationGridStackable) {
      @media only screen and (max-width: @largestMobileScreen) {
        .ui.stackable.grid .ui.fluid.vertical.pointing.menu .active.item::after {
          display: none;
        }
      }
    }
    // <-- here your addition ends
  }
```

Then at Line 1318
```less
& when (@variationMenuStackable) {
  /*--------------
      Stackable
  ---------------*/

  @media only screen and (max-width: @largestMobileScreen) {
    .ui.stackable.menu {
      flex-direction: column;
	  // here your addition starts -->
	  &.pointing .active.item::after when (@variationMenuPointing) {
			display: none;
	  }
	  // <-- here your addition ends
    }

```

**Review by lubber-de — APPROVED** [review]
LGTM

**Pull request merged**
