### PR TITLE
fixing both Bower and Composer package names

### PR DESCRIPTION
**Pull request by salaros**

### CODE REVIEW

**Comment by hammy2899** [comment]
Thanks for this, I will try to get these merged in the next few days 😃

**Comment by salaros** [comment]
Thanks! ✌️

**Comment by salaros** [comment]
How often `beta` branch is merged to `master`?

P.S. Thanks for keeping SUI alive!

**Comment by hammy2899** [comment]
We aim to make a release every 2 weeks. I am going to try and get a release today or tomorrow.

**Pull request merged**
