### PR TITLE
build(scripts): fix nightly exit codes

### PR DESCRIPTION
**Pull request by hammy2899**
Made changes to the nightly script and workflow so we can exit with code 0 so the action doesn't "fail" and alert us yet we can still prevent the publish steps from executing.

### CODE REVIEW

**Review by lubber-de — APPROVED** [review]
LGTM

**Comment by lubber-de** [comment]
Somehow github did not like the new yml-setting tonight 😢 Could you please re-investigate ?

**Comment by hammy2899** [comment]
Yea il take a look today before tonights run

**Comment by hammy2899** [comment]
Fixed https://github.com/fomantic/Fomantic-UI/pull/2286

**Pull request merged**
