### PR TITLE
[Icon] Make colored icon selector more specific

### PR DESCRIPTION
**Pull request by eikek**
## Description

Adds one more `.icon` to the icon color definition to make it work in nested lists.

## Testcase

https://jsfiddle.net/medc42zu/2/

## Closes

#1748

### CODE REVIEW

**Review by lubber-de — APPROVED** [review]
LGTM

**Review by exoego — APPROVED** [review]
LGTM

**Review by prudho — APPROVED** [review]
LGTM

**Comment by lubber-de** [comment]
@all-contributors please add @eikek for code

**Pull request merged**
