### PR TITLE
[Progress] limitValues setting limits values to 100 instead of percentages

### LINKED ISSUE #1689: [Progress] is stuck when total is not 100
## Testcase
https://jsfiddle.net/1rgLy39e/2/

## Screenshot (when possible)
progress_stuck

Same problem with sample on example :  https://fomantic-ui.com/modules/progress.html#frequently-updated-progress
progress_stuck_2

## Version
2.8.7

### PR DESCRIPTION
**Pull request by lubber-de**
## Description
The `limitValues` setting limits the values between 0 and 100. Instead it should limit the calculated precentages instead and calculate the actual values afterwards.

## Testcase
Click on the + icon. It should increase the progress
### Broken
It reduces the value and even by clicking many times on the + button the value is stuck
https://jsfiddle.net/lubber/q01tfzeb/6/

### Fixed
All fine
https://jsfiddle.net/lubber/q01tfzeb/12/

## Closes
#1689

### CODE REVIEW

**Comment by dutrieux** [comment]
I juste update you fixed sample to increment one by one (not ten by ten), and he seem to been **not working** : https://jsfiddle.net/b7ncLjxr/

**Comment by lubber-de** [comment]
@dutrieux 

> I juste update you fixed sample to increment one by one (not ten by ten), and he seem to been **not working** : https://jsfiddle.net/b7ncLjxr/

Thanks for pointing that out. This is a regression since #954. The values are being recalculated by their percentages. In case of low values compared to their totals this always resulted into the same values because of the rounded percents.

I fixed this now again. See your example using increments/decrements by 1 (instead of 10). It works now as expected
https://jsfiddle.net/lubber/q01tfzeb/10/

**Comment by dutrieux** [comment]
@lubber-de 
Thx for your work : I remark a strange thing : a rollback of the number of label, it is displayed quickly :
progress_1

**Comment by lubber-de** [comment]
@dutrieux 
> I remark a strange thing : a rollback of the number in label, it is displayed quickly :

Should also be fixed by 06292fa486f039298b415170ca7e78f1853d5fb9 now
Please try https://jsfiddle.net/lubber/q01tfzeb/12/

**Comment by dutrieux** [comment]
@lubber-de 
Ok thx : all seem to be ok

**Review by ko2in — APPROVED** [review]
LGTM.

**Comment by lubber-de** [comment]
@fomantic/maintainers Time to review this (if not done already)

**Review by ColinFrick — APPROVED** [review]

**Pull request merged**
